# Generated by Django 2.2.13 on 2020-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservisit',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
