# Generated by Django 2.2.13 on 2020-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbithole',
            name='bunnies_limit',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
