# Generated by Django 2.2.13 on 2022-02-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunnies', '0002_rabbithole_bunnies_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbithole',
            name='bunny_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
